### ISSUE TITLE
Disable the binary protocol option for memcache, it's awful for performance

### ISSUE THREAD

**Issue by bkosborne** [acquia/memcache-settings#3]
I recently upgraded a site from BLT 9 to 10, and as such have upgraded memcache to 2.0 and use the settings provided by this repo.

The settings file now enables the binary protocol for memcached, I guess because SASL requires it (not sure what SASL is but I don't think the majority of sites use it?)

```
// Settings for SASL Authenticated Memcached.
$settings['memcache']['options'][Memcached::OPT_BINARY_PROTOCOL] = TRUE;
```

This caused a very noticeable performance hit on the site:

![Screen Shot 2019-11-06 at 6 33 03 AM](https://user-images.githubusercontent.com/544886/68400490-221ebe00-0146-11ea-9610-5edb7442ece7.png)

You can see from this graph that as soon as I deployed the code update, the amount of time get operations took **increased 5x**.

Note also that the total throughput for get operations did not change (so it's not like I deployed code that was using the memcache more).

I recently turned this option off, and here's the new graph:

<img width="743" alt="Screen Shot 2019-11-07 at 10 07 49 AM" src="https://user-images.githubusercontent.com/544886/68400725-7de94700-0146-11ea-822b-f1cc51ff3a3d.png">

In the [PR that removed the memcache settings file from BLT](https://github.com/acquia/blt/pull/3801/files), the binary mode was not in there, so not sure why it was added in this repo.

Note that the [memcache README](https://git.drupalcode.org/project/memcache/blob/8.x-2.0/README.txt#L298) indicates this option should only be enabled under special circumstances.

**Comment by bkosborne** [comment]
@danepowell Hey, sorry to ping, I just wanted to check that someone from Acquia sees this at some point. Not sure if the issue queue for this small project is monitored much. I imagine some BLT users have this issue and don't realize it. I worked around this in our projects by overriding the setting. Note that I recently opened a support ticket with Acquia about memcache perf issues with ACSF, but I think it's unrelated to this (in case Acquia support ropes you in).

**Comment by danepowell** [comment]
Hey @bkosborne can you please submit a support ticket specifically requesting that the memcache documentation and sample code be updated to disable this setting? Or if you want to privately message me with your subscription info, I can relay it.

Sorry for the hoop-jumping, but this repo just mirrors the [memcache recommendations on docs.acquia.com](https://docs.acquia.com/acquia-cloud/performance/memcached/enable/). It can't be updated independently of those docs.

**Comment by danepowell** [comment]
Actually I was able to get your info so no need to open a support ticket yourself, although if you do it certainly wouldn't hurt :smile: This has been advocated for and will be reviewed internally. Cheers.

**Comment by bkosborne** [comment]
Great, thank you!

**Comment by aweingarten** [comment]
I was trying to reproduce the magic here but no dice.  I am not sure what is different. The first test has binary mode disabled.  The second run with it enabled again.

<img width="708" alt="Screen Shot 2020-02-21 at 5 48 44 PM" src="https://user-images.githubusercontent.com/6517820/75078024-7752c580-54d2-11ea-96f0-87ee65f5f7e1.png">

To confirm that it was enabled and disabled I ran the following 
`drush php-eval "var_dump(\Drupal\Core\Site\Settings::get('memcache'));"`

Looking for 
```
array(4) {
  ["options"]=>
  array(2) {
    [18]=>
    bool(true)
  }
```
The 18 true means binary is enabled.

I am thinking there is something else at play here. Maybe:
- Dedicated vs shared memcache
- Memcache module version

**Comment by danepowell** [comment]
@bkosborne is it possible that some other change caused your performance regression besides the binary protocol? Have you tried a/b testing with just the binary config turned on/off to confirm that's the culprit?

Results from @aweingarten don't seem to indicate an issue with this option. Obviously it could vary between applications.

**Comment by aweingarten** [comment]
The mystery here is compelling.   

I am going to retest later this week to see if evictions + binary mode might be responsible.  We have already optimized memcache to prevent evictions in our envs. Its possible that could explain the discrepency in results.  

@danepowell, one thing that could help situations like this would be to add memcache stats from signalfx to the stack metrics so we would have a better clue.  Like hit rate, eviction rate and memory percent?

**Comment by bkosborne** [comment]
@danepowell I'm quite sure it was the binary protocol change. I distinctly remember performing a code deploy where the only thing I changed was to disable binary protocol, after about a week or so of it being on and noticing the sluggish performance.

I also recently migrated sites from ACE multisite to ACSF, and during that migration, binary mode was enabled again (due to my misunderstanding of how the factory hooks worked). I noticed the sluggish performance and saw it in new relic. I again disabled it with a new code deploy and it went back to normal.

But really, given the significance of the performance impact I observed, I'm really surprised that other people have not reported this same issue to Acquia. It makes me think that somehow my situation is unique, but I'm not sure why it would be.

**Comment by bkosborne** [comment]
@aweingarten Out of curiosity, what has you interested in this issue if you're not also experiencing slow performance?

**Comment by aweingarten** [comment]
So I am interested because Drupal sucks when it comes to caching.  To bootstrap Drupal and serve a page from its page cache takes ~30 cache reads.  To build a page with layout builder can take ~200-300 memcache reads which is serious time.  

Given that we were hoping that this could help our load times and scaling.

**Comment by patrickcate** [comment]
Is there a way to detect when a site is using SASL authenticated memcache so the setting can be wrapped in an if statement?

**Comment by janusman** [comment]
I've done some recent A/B testing with a "typical" site and also found issues with the binary protocol. My testing ran various dimensions including Memcached::OPT_BINARY_PROTOCOL TRUE/FALSE, but also with/without compression, with/without primed caches, and across 4 different URLs. Tests also started with a pristine (just-restarted) memcached instance. 

Apparently in my testing, setting OPT_BINARY_PROTOCOL to false led to:

* greatly improved page performance (and drush performance) when cache is completely empty, decreasing time by about 84%
* slightly better performance on individual page loads when caches are primed (time decreased by 17.8%)

During testing, since Memcache was 128MB, there were no evictions. A curious thing is that the number of memcache reads/writes is very similar, however, the time spent in reads/writes was longer with OPT_BINARY_PROTOCOL than without.

I used XHProf to look directly at Memcached::getMulti() showed significant differences. Example: on a full cache, looking at 425 calls to https://www.php.net/manual/en/memcached.getmulti.php ... OPT_BINARY_PROTOCOL enabled took 0.79s, and disabled took 0.13s 

It feels that removing this here is safe for Acquia sites at least. Sites that need SASL authentication have different Acquia "magic" code which should take care of setting this properly (I think @aweingarten already saw this in PR #7 ... )

**Comment by bkosborne** [comment]
@janusman Thank for your testing. Your findings are consistent with mine. We have a lot of evictions on our sites because we run multisite/ACSF with lots of sites all sharing memcache, so we're not working with primed caches on some of our less popular sites.
